### ISSUE TITLE
Print-Job failed: 'client-error-document-format-not-supported'

### ISSUE THREAD

**Issue by xayo69** [gmuth/ipp-samples#2]
运行方法报出这个错误：IppOperationException: Print-Job failed: 'client-error-document-format-not-supported'
该如何解决？有没有详细的api说明文档提供？

**Comment by gmuth** [comment]
your printer does not support the format of the 'document'. e.g. if you send pdf the printer needs to support pdf and render the pdf.

**Comment by xayo69** [comment]
> your printer does not support the format of the 'document'. e.g. if you send pdf the printer needs to support pdf and render the pdf.

**Comment by xayo69** [comment]
ippJob = ippJobPrinter!!.printJob(
                printerFile!!,
                DocumentFormat.PDF,
                jobName(printerFile!!.name),
                pageRanges(2..5),
                Media.ISO_A4,
                ColorMode.Monochrome
            )
我现在需要打印的pdf格式的文件，现在这样设置的话就报错Print-Job failed: 'client-error-document-format-not-supported'，
这个该如何解决？

**Comment by gmuth** [comment]
The status code is produced by the printers firmware. The exception is thrown because the printer does not support your request. This expected behavior is called error handling.
