### ISSUE TITLE
IppOperationException: Print-Job failed: 'client-error-document-format-not-supported'

### ISSUE THREAD

**Issue by xayo69** [gmuth/ipp-samples#3]
ippJob = ippJobPrinter!!.printJob(
printerFile!!,
DocumentFormat.PDF,
jobName(printerFile!!.name),
pageRanges(2..5),
Media.ISO_A4,
ColorMode.Monochrome
)
我现在需要打印的pdf格式的文件，现在这样设置的话就报错Print-Job failed: 'client-error-document-format-not-supported'，
这个该如何解决？

**Comment by gmuth** [comment]
your printer does not support the format of the 'document'. e.g. if you send pdf the printer needs to support pdf and render the pdf

**Comment by xayo69** [comment]
> your printer does not support the format of the 'document'. e.g. if you send pdf the printer needs to support pdf and render the pdf

我目前的文件是pdf格式的文件，我用你的代码传入文件后就报错了Print-Job failed: 'client-error-document-format-not-supported' 我目前不知道该怎么弄好？

**Comment by xayo69** [comment]
> your printer does not support the format of the 'document'. e.g. if you send pdf the printer needs to support pdf and render the pdf

目前我这边文件是pdf格式的，你说的意思是我这边需要把pdf文件展示出来，再可以打印吗？

**Comment by gmuth** [comment]
please write in english

**Comment by xayo69** [comment]
The file here is in pdf format, do I need to display this pdf file before I can print it?

**Comment by xayo69** [comment]
Your example code is to support pdf file printing is it? I am very worried now, I do not know how to solve this problem, can you help me?

**Comment by gmuth** [comment]
The library supports sending documents in any format to printers via IPP.
Make sure you send (=print) a format your printer supports.
What formats does your printer support? Just look at attribute document-format-supported.
Once you found out you can select a format you want to provide.

**Comment by xayo69** [comment]
> The library supports sending documents in any format to printers via IPP. Make sure you send (=print) a format your printer supports. What formats does your printer support? Just look at attribute document-format-supported. Once you found out you can select a format you want to provide.

**Comment by xayo69** [comment]
> The library supports sending documents in any format to printers via IPP. Make sure you send (=print) a format your printer supports. What formats does your printer support? Just look at attribute document-format-supported. Once you found out you can select a format you want to provide.

Now I need to use your code to query the formats supported by the printer?

**Comment by gmuth** [comment]
I personally think the documentation and code is good enough to solve this.
Please create a pull request including your code as an example how to use the ipp-client library solving this.
The examples provided work fine as long as the printer meets the requirements (=supports pdf).
I am happy to offer paid support - sponsor my work https://github.com/sponsors/gmuth

**Comment by xayo69** [comment]
What's your email address? How did you get in touch? I am currently using your code do not know how to deal with this problem?

**Comment by gmuth** [comment]
I'll get in touch with you once the sponsorship has started. Minimum sponsorship for your use case is USD 500.

**Comment by xayo69** [comment]
> I'll get in touch with you once the sponsorship has started. Minimum sponsorship for your use case is USD 500.

ok
